# Generated by Django 2.1.5 on 2019-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Type something creative', max_length=511),
        ),
    ]
