# Generated by Django 2.1.5 on 2019-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='GIVE ME DESCRIPTION', max_length=511),
        ),
    ]
