# Generated by Django 2.1.5 on 2019-01-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190117_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date',)},
        ),
    ]
